-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('COMPLETE', 'NOT_COLLECTED', 'CANCELED', 'PENDING_PAYMENT', 'PENDING_COLLECTION', 'PENDING_PREPARE');

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "status" "OrderStatus" NOT NULL DEFAULT 'PENDING_PAYMENT';
